name: Joinly
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: '13.0'
configs:
  Debug: debug
  Release: release
targets:
  Joinly:
    type: application
    platform: macOS
    sources:
      - path: Joinly
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.qingteng.Joinly
        PRODUCT_NAME: Joinly
        SWIFT_VERSION: '6.0'
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Joinly
        INFOPLIST_KEY_CFBundleShortVersionString: $(MARKETING_VERSION)
        INFOPLIST_KEY_CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.video
        INFOPLIST_KEY_NSHumanReadableCopyright: Made By QingTengStudio
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        ENABLE_APP_SANDBOX: NO
